### ISSUE TITLE
Graphische Oberfläche zum Selektierung von Methoden, welche gePPPed werden sollen

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [HPI-SWA-Teaching/SWT16-Project-08#11]
### 2 GUI (25 Personenstunden):
- "As a user, I want to interact with the PPP in a GUI in which I can manually select the methods/classes/packages to be PPPed."
- Akzeptanzkriterien:
  - PPP ist in das Apps-Menü integriert.
  - Man kann 1..* Packages auswählen, darin 1..* Klassen und darin 1..* Methoden (wie im Lint-Browser).
  - Die ausgewählten Dinge können auf Knopfdruck gePPPed werden.

  - Per Rechtsklick kann ein Menü aufgerufen werden, dass es erlaubt, alle, keine, oder invertierte Elemente auszuwählen

**Comment by jon-kroko** [comment]
Still todo:
- ~~*in PPP-Kategorie hinüberziehen*~~
- ~~*das gleiche Procedere mit Klassen und Methoden*~~
- Layout
- Testen, ob die ausgewählten Methoden tatsächlich gePPPed werden
- Der Knopf soll PPP aktivieren
- ~~*currectSel und selCategories doppelt gemoppelt??*~~
- Selection (**Mehrfachauswahl!!1!11!!**, ~~selected categories/classes/methods aktualisieren~~)
  - ~~drei Instanzvariablen für arten von selections~~

**Comment by jaytrenti** [comment]
Problem: Selektoren können mehrmals vergeben werden (Polymorphie), müssen wir das in der Methodenliste extra handlen?

**Comment by jaytrenti** [comment]
PSA: damit der PPPButton funktioniert, MUSS unser PPP als Standard-Printer eingestellt werden, nicht nur damit er im Browser angezeigt wird

**Comment by jaytrenti** [comment]
Bug Report: Wenn man eine Kategorie deselected, werden die Methoden nicht aktualisiert, und die Klassen nur fehlerhaft. Will man dann eine Klasse selecten/deselecten, kommt es zu Out-of-Bounds-Crashes.
