### ISSUE TITLE
Argumente sinnvoll benennen, sodass man überall den erwarteten Argumenttypen ablesen kann

### ISSUE THREAD

**Issue by jon-kroko** [HPI-SWA-Teaching/SWT16-Project-08#52]

**Comment by grittaweisheit** [comment]
#### noch zu tun:

PPPVisitor:
- evtl. statt aNode jedes Mal den Typ Node, den man erwartet

PPPSettingsProfile:
- [x] dotAfterReturn:
- [x] newlineAfterTemporaryDeclaration:
- [x] spaceAroundBinaryOperator:
- [x] spaceBeforeReturn:


(in Zusammenhang mit den AST-Typen:)
AssignmentNode:
- [x] value
- [x] variable

BlockNode:
- [x] bodySequence

MessageNode:
- [x] arguments (wahrscheinlich OrderedCollection oder Array, ...)
- [x] receiver, selector (ist Selector eigener Typ?)

**Comment by jon-kroko** [comment]
Done, see 0698686b137d993663e76efcdef1622962e4303
