### ISSUE TITLE
Übersicht über mögliche Typen der AST-Kinder jedes Knotentyps erstellen

### ISSUE THREAD

**Issue by jon-kroko** [HPI-SWA-Teaching/SWT16-Project-08#53]
![photo_2019-05-23_10-33-15](https://user-images.githubusercontent.com/37243299/58238108-ed10e180-7d46-11e9-8b9e-d4f079374acf.jpg)
![photo_2019-05-23_10-33-18](https://user-images.githubusercontent.com/37243299/58238113-ef733b80-7d46-11e9-9bb9-6cae21cf7cfa.jpg)
![photo_2019-05-23_10-33-20](https://user-images.githubusercontent.com/37243299/58238119-f1d59580-7d46-11e9-89bb-15208e18a4ed.jpg)
![photo_2019-05-23_10-33-23](https://user-images.githubusercontent.com/37243299/58238124-f306c280-7d46-11e9-9c29-74c4cf6d34ca.jpg)
![photo_2019-05-23_10-33-25](https://user-images.githubusercontent.com/37243299/58238127-f732e000-7d46-11e9-9874-ea4cc0ae1ee0.jpg)
![photo_2019-05-23_10-33-28](https://user-images.githubusercontent.com/37243299/58238129-f8fca380-7d46-11e9-8e11-3a0431f8893e.jpg)

**Comment by jon-kroko** [comment]
![photo_2019-05-23_10-39-27](https://user-images.githubusercontent.com/37243299/58238191-16317200-7d47-11e9-812d-8332cd4f65b4.jpg)

**Comment by grittaweisheit** [comment]
#### noch ungeklärt:
AssignmentNode:
- [ ] value
- [ ] variable

BlockNode:
- [ ] bodySequence

MessageNode:
- [ ] arguments (wahrscheinlich OrderedCollection oder Array, ...)
- [ ] receiver, selector (ist Selector eigener Typ?)

**Comment by jon-kroko** [comment]
Brauchen wir das noch, wenn wir jetzt sinnvolle Bezeichnungen (z. B. aValueNode) für die Setter-Variablen haben?
