### ISSUE TITLE
Comments are printed in weird places...

### ISSUE THREAD

**Issue by jon-kroko** [HPI-SWA-Teaching/SWT16-Project-08#57]
### Vorher:
![Bildschirmfoto 2019-05-28 um 12.03.12.png](https://images.zenhubusercontent.com/5cc581deba27a75ea1e3f782/8b75193f-fa7e-42a2-a1f7-fef4a8ed526c)

### Nachher:
![Bildschirmfoto 2019-05-28 um 12.04.36.png](https://images.zenhubusercontent.com/5cc581deba27a75ea1e3f782/330dee47-1164-4baa-af14-4bb9ba5c2b72)

**Comment by grittaweisheit** [comment]
In Cascades the Comment is printed bevore the whole cascade even though it was placed somewhere in it
