### ISSUE TITLE
Waiting Icon

### ISSUE THREAD

**Issue by jon-kroko** [HPI-SWA-Teaching/SWT16-Project-08#60]
- So etwas wie eine kleine Sanduhr, die während des PPPens angezeigt wird (denn das kann ja durchaus mal ein Bisschen länger dauern).

**Comment by tom95** [comment]
Wenn ihr da schon einen Richtwert hättet, ab wie viel Methoden es mehr als zB 1s dauert, würde das noch helfen die Wichtigkeit der Story einzuschätzen :)
