### ISSUE TITLE
Der PPP formatiert noch nicht alle korrekt

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [HPI-SWA-Teaching/SWT16-Project-08#9]
#### INFO:
Ein +1 bedeutet, dass der Bug bereits durch eine US oder einen Issue in Bearbeitung ist. Übrige Kommentare sind noch verbleibende Fehler, die für den nächsten Sprint in die Pipeline aufgenommen werden sollten.

Der PPP sollte mit möglichst vielen corner cases klarkommen und diese auch korrekt formatieren. 

#### TODO:
- Nach solchen corner cases suchen.
- Die corner cases hier als Kommentare nach dem unten aufgeführten Schema auflisten.
- Weiter Issues / user stories erstellen, in denen diese corner cases gefixet werden und Tests für diese geschrieben werden.

#### Methode
``` Hier die Methode hinzufügen ```
#### Erwartete Formatierung
``` Hier die Methode, so formatiert, wie es sein sollte hin ```
#### Ausgegebene Formatierung des PPP
``` Hier die Ausgabe des PPP hin ```

### Test Script
``` Hinzufügen TODO ```

**Comment by MichaelBuessemeyer** [comment]
see #13

**Comment by MichaelBuessemeyer** [comment]
Der `PPPParser` unterstütz nicht mehrere Pragmas. Es gibt den Fehler : 
``` Method is malformed. Check check syntax near character ... ``` 
Bsp: 
```
test
<test>
<test2>
self hello
```

**Comment by MichaelBuessemeyer** [comment]
Der PPPParser geht davon aus, das zuerst die temporären Varibalen kommen und dann die Pragmas. Eigentlich ist die Reihenfolge irrelevant. Folglich lässt sich 
```
test
<hello>
| hello |
^ self
``` 
nicht compilen.

**Comment by grittaweisheit** [comment]
Der  PPPPrinter geht bei einer Verschachtelungstiefe >=2 kaputt

**Comment by grittaweisheit** [comment]
Lange Zeilen werden nicht umgebrochen

**Comment by jaytrenti** [comment]
Kaskaden werden nicht korrekt umgebrochen / eingerückt

**Comment by jaytrenti** [comment]
PPP löscht Kommentare
